language: ruby

# env:
#   matrix:
#     - "RAILS_MASTER=0"
#     - "RAILS_MASTER=1"

rvm:
  - 2.2

services:
  - docker

sudo: required

before_install:
    - docker info
    - docker-compose build

script: docker-compose run app ./script/ci/ci.parallel spec
