language: ruby

env:
  matrix:
    - "SPLIT=0"
    - "SPLIT=1"
    - "SPLIT=2"

rvm:
  - 2.2

services:
  - docker

sudo: required

install:
    - docker info
    - docker-compose build

script: bash -c "case $SPLIT in 0) docker-compose run app ./script/ci/ci.parallel spec ;; 1) docker-compose run app ./script/ci/ci.parallel plugin ;; 2) docker-compose run app ./script/ci/ci.parallel qunit ;; esac"
